"""
Vault Module - Handles encryption for secure history storage.
"""

import os
import base64
import logging
import hashlib
import sys
from pathlib import Path
from typing import Optional
from dotenv import load_dotenv

# Load environment variables from .env if present
load_dotenv()

# Setup logger
logger = logging.getLogger(__name__)

try:
    from cryptography.fernet import Fernet, InvalidToken
    from cryptography.hazmat.primitives import hashes
    from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
    CRYPTOGRAPHY_AVAILABLE = True
except ImportError:
    CRYPTOGRAPHY_AVAILABLE = False


class Vault:
    """Manages encryption keys and secure data transformation."""
    
    def __init__(self, vault_dir: Optional[Path] = None):
        """Initialize vault with a storage directory."""
        if vault_dir:
            self.vault_dir = vault_dir
        else:
            self.vault_dir = Path.home() / ".passforge"
            
        self.vault_dir.mkdir(parents=True, exist_ok=True)
        self.key_file = self.vault_dir / ".vault.key"
        self._fernet = None
        
        if CRYPTOGRAPHY_AVAILABLE:
            self._init_fernet()

    def _init_fernet(self):
        """
        Initialize the Fernet encryption instance.
        Prioritizes PASSFORGE_API_KEY from environment/.env.
        """
        api_key = os.getenv("PASSFORGE_API_KEY")
        key = None

        if api_key:
            # Derive Fernet-compatible key (32 bytes base64 encoded) from API key
            key_bytes = hashlib.sha256(api_key.encode()).digest()
            key = base64.urlsafe_b64encode(key_bytes)
        elif self.key_file.exists():
            # Fallback to legacy key file if it exists
            try:
                with open(self.key_file, 'rb') as f:
                    key = f.read()
            except Exception as e:
                logger.error(f"Failed to read legacy key file: {e}")
        
        if not key:
            # Encryption will be inactive if no key is found
            return
        
        try:
            self._fernet = Fernet(key)
        except Exception as e:
            logger.error(f"Failed to initialize Fernet with key: {e}")
            self._fernet = None

    @staticmethod
    def ensure_secure_mode() -> bool:
        """
        Ensure the user has an encryption key set.
        Returns True if key is set, False if not.
        """
        from colorama import Fore, Style
        vault = Vault()
        if vault.is_active:
            return True
            
        print(f"\n{Fore.YELLOW}⚠️  Security Warning: No Encryption Key Found!{Style.RESET_ALL}")
        print("To securely store and view your password history, you must set an encryption key.")
        print("\nHow to fix:")
        print(f"1. Create a {Fore.CYAN}.env{Style.RESET_ALL} file in the project root.")
        print(f"2. Add {Fore.GREEN}PASSFORGE_API_KEY=your_strong_secret{Style.RESET_ALL} to it.")
        
        # Try to offer auto-generation if in a TTY
        if sys.stdin.isatty():
            print(f"\nWould you like me to generate a secure key for you in a .env file? (y/n)")
            try:
                choice = input("> ").lower().strip()
                if choice == 'y':
                    import secrets
                    key = secrets.token_urlsafe(32)
                    try:
                        with open(".env", "a") as f:
                            f.write(f"\n# Generated by PassForge\nPASSFORGE_API_KEY={key}\n")
                        # Reload env
                        from dotenv import load_dotenv
                        load_dotenv()
                        # Re-verify
                        if Vault().is_active:
                            print(f"{Fore.GREEN}[OK] .env file updated with a new secure key.{Style.RESET_ALL}")
                            return True
                    except Exception as e:
                        print(f"{Fore.RED}[ERR] Failed to write to .env: {e}{Style.RESET_ALL}")
            except (KeyboardInterrupt, EOFError):
                print()
                
        print(f"{Fore.YELLOW}History features are disabled until a key is set.{Style.RESET_ALL}")
        return False

    @property
    def is_active(self) -> bool:
        """Check if encryption is available and initialized."""
        return CRYPTOGRAPHY_AVAILABLE and self._fernet is not None

    def encrypt(self, text: str, strict: bool = False) -> str:
        """
        Encrypt a string. 
        Falling back to plaintext by default unless strict=True.
        """
        if not self.is_active or not text:
            if strict and text:
                raise RuntimeError("Vault is not active, cannot encrypt strictly")
            return text
            
        try:
            encrypted = self._fernet.encrypt(text.encode('utf-8'))
            return encrypted.decode('ascii')
        except (InvalidToken, Exception) as e:
            logger.warning(f"Encryption failed: {e}")
            if strict:
                raise
            return text

    def decrypt(self, encrypted_text: str, strict: bool = False) -> str:
        """
        Decrypt a base64 encoded string.
        Falling back to input text by default unless strict=True.
        """
        if not self.is_active or not encrypted_text:
            if strict and encrypted_text:
                raise RuntimeError("Vault is not active, cannot decrypt strictly")
            return encrypted_text
            
        try:
            decrypted = self._fernet.decrypt(encrypted_text.encode('ascii'))
            return decrypted.decode('utf-8')
        except (InvalidToken, Exception) as e:
            logger.warning(f"Decryption failed: {e}")
            if strict:
                raise
            # If decryption fails (e.g. wrong key or plain text), return as is
            return encrypted_text
